#!/usr/bin/env python3
"""Print a LabelsControlPro preview image with Brother QL raster commands.

This bypasses Windows GDI layout and Brother Printing Preferences. It still sends
RAW bytes through the selected Windows printer queue, but the bytes are Brother QL
raster commands generated by the brother_ql package.
"""

import argparse
import base64
import ctypes
from ctypes import wintypes
import io
import json
import sys

try:
    from PIL import Image
    if not hasattr(Image, "ANTIALIAS"):
        Image.ANTIALIAS = Image.Resampling.LANCZOS
    from brother_ql import BrotherQLRaster, create_label
except Exception as exc:  # pragma: no cover - reported to caller as JSON
    print(json.dumps({
        "status": "error",
        "error": "Missing Python dependencies. Install with: py -m pip install -r scripts/requirements-brother-ql.txt",
        "details": str(exc),
    }))
    sys.exit(1)


class DOCINFOA(ctypes.Structure):
    _fields_ = [
        ("pDocName", wintypes.LPCSTR),
        ("pOutputFile", wintypes.LPCSTR),
        ("pDatatype", wintypes.LPCSTR),
    ]


winspool = ctypes.WinDLL("winspool.drv")
OpenPrinter = winspool.OpenPrinterW
OpenPrinter.argtypes = [wintypes.LPWSTR, ctypes.POINTER(wintypes.HANDLE), wintypes.LPVOID]
OpenPrinter.restype = wintypes.BOOL
ClosePrinter = winspool.ClosePrinter
ClosePrinter.argtypes = [wintypes.HANDLE]
ClosePrinter.restype = wintypes.BOOL
StartDocPrinter = winspool.StartDocPrinterA
StartDocPrinter.argtypes = [wintypes.HANDLE, wintypes.DWORD, ctypes.POINTER(DOCINFOA)]
StartDocPrinter.restype = wintypes.DWORD
EndDocPrinter = winspool.EndDocPrinter
EndDocPrinter.argtypes = [wintypes.HANDLE]
EndDocPrinter.restype = wintypes.BOOL
StartPagePrinter = winspool.StartPagePrinter
StartPagePrinter.argtypes = [wintypes.HANDLE]
StartPagePrinter.restype = wintypes.BOOL
EndPagePrinter = winspool.EndPagePrinter
EndPagePrinter.argtypes = [wintypes.HANDLE]
EndPagePrinter.restype = wintypes.BOOL
WritePrinter = winspool.WritePrinter
WritePrinter.argtypes = [wintypes.HANDLE, wintypes.LPVOID, wintypes.DWORD, ctypes.POINTER(wintypes.DWORD)]
WritePrinter.restype = wintypes.BOOL


def raw_write_to_windows_queue(printer_name: str, document_name: str, data: bytes) -> None:
    handle = wintypes.HANDLE()
    if not OpenPrinter(printer_name, ctypes.byref(handle), None):
        raise OSError(f"Could not open Windows printer queue: {printer_name}")
    try:
        info = DOCINFOA(document_name.encode("ascii", "replace"), None, b"RAW")
        if not StartDocPrinter(handle, 1, ctypes.byref(info)):
            raise OSError("Could not start RAW print document")
        try:
            if not StartPagePrinter(handle):
                raise OSError("Could not start RAW print page")
            try:
                written = wintypes.DWORD(0)
                buffer = ctypes.create_string_buffer(data)
                if not WritePrinter(handle, buffer, len(data), ctypes.byref(written)):
                    raise OSError("Could not write RAW Brother QL data")
                if written.value != len(data):
                    raise OSError(f"RAW write incomplete: {written.value} of {len(data)} bytes")
            finally:
                EndPagePrinter(handle)
        finally:
            EndDocPrinter(handle)
    finally:
        ClosePrinter(handle)


def load_preview_image(payload: dict) -> Image.Image:
    data_url = payload.get("preview_image_data_url") or ""
    if not data_url:
        raise ValueError("No preview image was supplied by the frontend")
    if "," in data_url:
        data_url = data_url.split(",", 1)[1]
    raw = base64.b64decode(data_url)
    image = Image.open(io.BytesIO(raw)).convert("RGB")
    return image


def render_to_brother_raster(payload: dict, label_width_mm: float, label_length_mm: float) -> bytes:
    model = str(payload.get("brother_ql_model") or "QL-820NWB")
    # Use continuous tape identifiers (e.g. "62") for variable app-controlled
    # lengths like 62x60, 62x75, 62x150. brother_ql only has die-cut IDs for
    # real die-cut stock such as 62x29 and 62x100; custom 62x60/75 are not IDs.
    label_size = str(payload.get("brother_ql_label_size") or round(label_width_mm))
    threshold = int(payload.get("brother_ql_threshold") or 70)

    image = load_preview_image(payload)

    # Brother QL-820NWB: 300 dpi. For 62mm endless tape brother_ql expects the
    # raster image width to become the printable tape width (696 dots for 62mm),
    # while image height is the variable cut length. The UI preview is landscape
    # (length x width), so render to length x printable_width and ask brother_ql
    # to rotate 90 degrees. This matches the documented endless-label pipeline.
    dpi = 300
    printable_width_dots = max(1, int(round((label_width_mm / 25.4) * dpi)))
    if round(label_width_mm) == 62:
        printable_width_dots = 696
    length_dots = max(1, int(round((label_length_mm / 25.4) * dpi)))
    image = image.resize((length_dots, printable_width_dots), Image.Resampling.LANCZOS)

    qlr = BrotherQLRaster(model)
    create_label(qlr, image, label_size, red=False, threshold=threshold, cut=True, rotate=90)
    return bytes(qlr.data)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--payload", required=True)
    parser.add_argument("--printer", required=True)
    parser.add_argument("--width-mm", required=True, type=float)
    parser.add_argument("--length-mm", required=True, type=float)
    parser.add_argument("--dry-run", action="store_true", help="Generate Brother QL raster bytes but do not send to printer")
    args = parser.parse_args()

    try:
        with open(args.payload, "r", encoding="utf-8") as fh:
            payload = json.load(fh)
        data = render_to_brother_raster(payload, args.width_mm, args.length_mm)
        if not args.dry_run:
            raw_write_to_windows_queue(args.printer, "LabelsControlPro Brother QL raster", data)
        print(json.dumps({
            "status": "dry_run_ok" if args.dry_run else "printed",
            "printer": args.printer,
            "printer_profile": "brother_ql_raster",
            "render_mode": "brother_ql_raster_raw",
            "label_width_mm": args.width_mm,
            "label_length_mm": args.length_mm,
            "bytes": len(data),
        }))
        return 0
    except Exception as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
